---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/name: hybrid-cloud-backend
    app.kubernetes.io/part-of: hybrid-cloud-demo
  name: hybrid-cloud-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybrid-cloud-backend
  template:
    metadata:
      labels:
        app: hybrid-cloud-backend
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          image: "will-be-replaced by pipeline"
          imagePullPolicy: "IfNotPresent"
          name: "hybrid-cloud-backend"
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          resources:
            limits:
              memory: "1200Mi"
              cpu: "750m"
            requests:
              memory: "500Mi"
              cpu: "500m"
