---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app.kubernetes.io/part-of: hybrid-cloud-demo
  name: hybrid-cloud-backend
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: hybrid-cloud-backend
