---
apiVersion: v1
kind: Service
metadata:
  annotations:
    skupper.io/proxy: http
    skupper.io/target: hybrid-cloud-backend.hybrid-cloud-demo
  name: hybrid-cloud-backend-skupper
spec:
  ports:
    - name: http
      port: 80
  type: LoadBalancer
