---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hybrid-cloud-backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/window: "16s"
    spec:
      serviceAccountName: hybrid-cloud-demo-sa
      containerConcurrency: 1
      containers:
        - image: quay.io/rhdevelopers/hybrid-cloud-demo-backend
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/live
          readinessProbe:
            httpGet:
              path: /health/ready
