---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hybrid-cloud-backend
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/window: "16s"
    spec:
      serviceAccountName: hybrid-cloud-demo-sa
      containerConcurrency: 1
      containers:
        - name: user-container
          image: image-registry.openshift-image-registry.svc:5000/hybrid-cloud-demo/hybrid-cloud-backend:v1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/live
          readinessProbe:
            httpGet:
              path: /health/ready
